### ISSUE TITLE
typo: 'Large' should be 'large'

### ISSUE THREAD

**Issue by climatebrad** [learn-co-curriculum/dsc-inheritance-lab#1]
In the Gorilla section:

> * Have a size of 'Large'

should be 

>  * Have a size of 'large'

**Comment by climatebrad** [comment]
minor note: gorillas are omnivores, not herbivores.

**Comment by sumedh10** [comment]
Thanks for reporting this. Apparently, _most_ gorillas are herbivores, so we are going to leave it as is ;)
